# Generated by Django 5.2.7 on 2025-12-04 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_clientassignment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clientassignment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="clientassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="clientassignment",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lawyer_assignment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clientassignment",
            name="lawyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
