# Generated by Django 5.2.7 on 2025-12-04 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_clientassignment_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clientassignment",
            unique_together={("lawyer", "client")},
        ),
    ]
