# Generated by Django 5.2.7 on 2025-11-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_extracted_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="clauses_found",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="risk_score",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
