# Generated by Django 5.2.7 on 2025-11-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_clauses_found_document_risk_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
