# Generated by Django 5.2.7 on 2025-11-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_document_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="analyzed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("analyzed", "Analyzed")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
